# Generated by Django 5.2.3 on 2025-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
